version: '3'

services:
  db:
    container_name: bulletindb
    image: mongo:4.2.1-bionic
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27017:27017'
